services:

  frontend:
    image: rodribaeza/front-despacho:latest
    container_name: front_despacho
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - NODE_ENV=production

networks: {}
